name: tildec
favicon: null
layout_spectrum: 0.25086
typography_spectrum: 0.32295
title: Random Ramblings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01040d'
    - '#0050c1'
    - '#91b8d7'
    - '#6d607b'
    - '#e5bc62'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
